### ISSUE TITLE
Clarifai Celebrity recognition fails

### ISSUE THREAD

**Issue by jaapvanblaaderen** [WoodWing/elvis-image-recognition#11]
Celebrity recognition fails with the following error:

```
[05-04-2018 13:52:02.769] [INFO]  Image recognition finshed for asset: 6-bx3-ARK6ZAzY0SV_ZW6i (12-Selected-Photographs-From-The-Competition-Urban-Photographer-of-the-Year-2015-4.jpg)
[05-04-2018 13:52:39.512] [INFO]  Image recognition started for asset: 85gJ36WvajN80QGGcU95de
[05-04-2018 13:52:40.617] [INFO]  Image recognition finshed for asset: 85gJ36WvajN80QGGcU95de (26930DC800000578-2993023-image-a-7_1426239928156.jpg)
[05-04-2018 13:53:54.872] [INFO]  API call received: OPTIONS “/api/recognize” with body: {}
[05-04-2018 13:53:54.880] [INFO]  API call received: POST “/api/recognize” with body: {“q”:“id:8oi0_wD04REAFrc0pfisnJ”,“models”:[“aaa03c23b3724a16a56b629203edc62c”,“bd367be194cf45149e75f01d59f77ba7”,“eee28c313d69466f836ab83287a54ed9",“c386b7a870114f4a87477c0824499348”,“e0be3b9d6a454f0493ac3a30784001ff”,“e466caa0619f444ab97497640cefc4dc”]}
[05-04-2018 13:53:54.901] [INFO]  Processing in-progress: 208f7358-4aed-417a-852e-30c2417cf380, total hits: 1, startIndex: 0, batchSize: 5, hits found: 1, query: {“QueryStringQuery”:{“queryString”:“(id:8oi0_wD04REAFrc0pfisnJ) AND assetDomain:image”}}
[05-04-2018 13:53:54.901] [INFO]  Image recognition started for asset: 8oi0_wD04REAFrc0pfisnJ
[05-04-2018 13:53:55.546] [ERROR] Image recognition failed for asset: 8oi0_wD04REAFrc0pfisnJ. Error details:
Error: An error occurred while getting celebrity info from Clarifai: {
 “code”: 21202,
 “description”: “Invalid model argument”,
 “details”: “min_value, max_concepts and select_concepts not supported for model ‘e466caa0619f444ab97497640cefc4dc’“,
 “req_id”: “d54444d9f9a04de7aff1310968d09c9b”
}
   at clarifai.models.predict.then.catch (/Users/cassone/Desktop/elvis-image-recognition-master/src/app/service/clarifai.ts:106:16)
   at tryCallOne (/Users/cassone/Desktop/elvis-image-recognition-master/node_modules/promise/lib/core.js:37:12)
   at /Users/cassone/Desktop/elvis-image-recognition-master/node_modules/promise/lib/core.js:123:15
   at flush (/Users/cassone/Desktop/elvis-image-recognition-master/node_modules/asap/raw.js:50:29)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by siebrand** [comment]
It would probably be good to document how the Clarifai application was configured, as there are a lot of options there that I at least haven't mastered yet.

**Comment by jaapvanblaaderen** [comment]
True. I expect in this case that they changed something in their API which leads to this failure. Looks like stricter argument checking.
